In [1]:
import torch

In [9]:
x = torch.empty(5,3)
x

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
y = torch.rand(5,3)
y

tensor([[0.3937, 0.7199, 0.7893],
        [0.7177, 0.2223, 0.7669],
        [0.2992, 0.2707, 0.2945],
        [0.9508, 0.0454, 0.5486],
        [0.8586, 0.6667, 0.3290]])

In [11]:
z = torch.zeros(5,3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
full = torch.full((2,3), fill_value=8)
full

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [14]:
torch.tensor([[3.7, 4], [9, 5]])

tensor([[3.7000, 4.0000],
        [9.0000, 5.0000]])

In [18]:
torch.rand_like(full)

tensor([[0.1457, 0.2278, 0.6312],
        [0.1606, 0.7166, 0.7153]])

In [20]:
full = full.to(torch.float32)
full

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [22]:
a = full.clone()
a

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [23]:
### Arithmetic tensors

In [26]:
full.size()

torch.Size([2, 3])

In [27]:
full

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [32]:
a2 = a+7
a2

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [33]:
torch.add(a2, full)

tensor([[23., 23., 23.],
        [23., 23., 23.]])

In [34]:
full.add(a2)

tensor([[23., 23., 23.],
        [23., 23., 23.]])

In [35]:
# when you use the underscore (in-place operation)
# it changes the actual original tensor!

full.add_(a2)

tensor([[23., 23., 23.],
        [23., 23., 23.]])

In [36]:
full

tensor([[23., 23., 23.],
        [23., 23., 23.]])

In [37]:
### Matrix multiplication in Pytorch

In [40]:
f = full.T
f

tensor([[23., 23.],
        [23., 23.],
        [23., 23.]])

In [45]:
print(f.size())
print(a2.size())

torch.Size([3, 2])
torch.Size([2, 3])


In [47]:
# matrix multiplication

mult = f.mm(a2)
mult

tensor([[690., 690., 690.],
        [690., 690., 690.],
        [690., 690., 690.]])

In [48]:
mult[:1]

tensor([[690., 690., 690.]])

In [49]:
mult[1:]

tensor([[690., 690., 690.],
        [690., 690., 690.]])

In [51]:
single = mult[1,2]
single

tensor(690.)

In [53]:
single.item()

690.0

In [54]:
# reshaping or re-arranging

d = torch.rand(4,4)

In [55]:
d

tensor([[9.5742e-01, 7.8796e-01, 9.6498e-03, 2.4834e-01],
        [2.2241e-01, 3.6432e-01, 6.8225e-01, 9.7895e-01],
        [5.8627e-01, 8.9360e-01, 5.2691e-04, 1.6381e-02],
        [1.5449e-01, 9.9483e-01, 8.7166e-01, 1.7313e-01]])

In [56]:
d.view(16)

tensor([9.5742e-01, 7.8796e-01, 9.6498e-03, 2.4834e-01, 2.2241e-01, 3.6432e-01,
        6.8225e-01, 9.7895e-01, 5.8627e-01, 8.9360e-01, 5.2691e-04, 1.6381e-02,
        1.5449e-01, 9.9483e-01, 8.7166e-01, 1.7313e-01])

In [57]:
d.view(-1,8)

# when you put -1, it infers the shape from the other dimension you have inputted

tensor([[9.5742e-01, 7.8796e-01, 9.6498e-03, 2.4834e-01, 2.2241e-01, 3.6432e-01,
         6.8225e-01, 9.7895e-01],
        [5.8627e-01, 8.9360e-01, 5.2691e-04, 1.6381e-02, 1.5449e-01, 9.9483e-01,
         8.7166e-01, 1.7313e-01]])

In [60]:
d.view(2,8)

tensor([[9.5742e-01, 7.8796e-01, 9.6498e-03, 2.4834e-01, 2.2241e-01, 3.6432e-01,
         6.8225e-01, 9.7895e-01],
        [5.8627e-01, 8.9360e-01, 5.2691e-04, 1.6381e-02, 1.5449e-01, 9.9483e-01,
         8.7166e-01, 1.7313e-01]])

In [61]:
d.numel()

# num of elements

16

In [63]:
h = torch.rand(2, 3, 4)
h

tensor([[[0.0027, 0.4672, 0.9186, 0.3335],
         [0.9897, 0.8204, 0.9246, 0.4102],
         [0.1097, 0.7819, 0.1359, 0.7604]],

        [[0.1296, 0.2414, 0.7882, 0.2246],
         [0.0575, 0.0826, 0.8970, 0.2812],
         [0.8638, 0.2689, 0.8598, 0.1324]]])

In [65]:
h.size()

torch.Size([2, 3, 4])

In [66]:
h.permute(1, 2, 0) # moves first dimension to last

tensor([[[0.0027, 0.1296],
         [0.4672, 0.2414],
         [0.9186, 0.7882],
         [0.3335, 0.2246]],

        [[0.9897, 0.0575],
         [0.8204, 0.0826],
         [0.9246, 0.8970],
         [0.4102, 0.2812]],

        [[0.1097, 0.8638],
         [0.7819, 0.2689],
         [0.1359, 0.8598],
         [0.7604, 0.1324]]])

### Autograd

autograd package for backprop (autodifferentiation, etc)

- must have `requires_grad` on
- or be results of tensors that have `requires_grad` on



In [70]:
g = torch.ones(2,5, requires_grad=True)
g

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [71]:
g.detach() # returns tensor without requires grad

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [74]:
j = g * 3
j.requires_grad

True

In [75]:
j.grad_fn

^ the gradient function is multiplication backward and it's 0

In [99]:
### Backprop

goop = torch.tensor(10.0, requires_grad=True)
poop = 3 * l
poop.backward
goop.backward

<bound method Tensor.backward of tensor(10., requires_grad=True)>

In [100]:
goop.grad

In [83]:
### recall, you can check your gradient using gradcheck